### ISSUE TITLE
File retriever should check for valid HTTP status code

### ISSUE THREAD

**Issue by proligde** [bestform/souparchive#1]
Steps to Reproduce:

- Archive your soup

Expected Result:

- All images are saved

Actual Result:

- More than 50% of the images seem corrupted and can't be opened.

Note:

The files (in this case images) are in fact not corrupted but contain a HTML page stating that there was an error. They seem to be sent with a HTTP Status Code 5xx (502 in this case) that should prevent the retriever from persisting the response to the file system.

**Comment by bestform** [comment]
Fixed in d325a0b.
Thanks for the report.

**Comment by proligde** [comment]
It is not fixed completely, since the file is still created with 0 bytes length.
